don't suppress exception on aexit
sbtinstruments/aiomqtt pull request #232
Opened 2023-07-11 19:00 UTC by edenhaus

With #216 the "early out on disconnected" code was move from the function `__aexit__` to `disconnect`. The `disconnect` function is called inside a try/except block in the function `__aexit__`, which suppresses the disconnected exception. This results in that the context manager exits without exception also when there was a disconnect-exception.

Example:
- start mqtt broker
- run a similar code:
```python
async with Client("localhost") as client:
    async with client.messages() as messages:
        await client.subscribe("humidity/#")
        async for message in messages:
            print(message.payload)
```
- shutdown broker

expection: I get some sort of exception
actual: no exception, only a log entry.

This bug was found on the upgrade from `0.16.1` to `1.0.0`. Afterwards the following test was failing https://github.com/DeebotUniverse/client.py/blob/3d7467e3dcf338e9d848dd5fb3ad32a5ee7fab8e/tests/test_mqtt_client.py#L76C1-L76C1
The test test the described example above.

2023-07-11 20:06 UTC, frederikaalund requested changes
Hi Robert, thanks for opening this pull request. 👍  Let me have a look. :)

You're right. This seems like a regression. Indeed, the client should raise (the Exception that caused a disconnect) on exit. The current implementation erroneously suppresses (and logs) this disconnect exception. That's my bad; I missed it in the code review. Good thing that you had a test case for it. If you don't mind, could you implement a similar test case here in aiomqtt? 👍 

In any case, I like this PR overall. I only have requests for minor changes. See my review for details. Let me know if you have any questions. Also, you need to fix the formatting/style issues (see the CI runs for details).

Thanks again for opening this pull request.

Best regards,
~Frederik

2023-07-11 20:06 UTC, frederikaalund commented on aiomqtt/client.py
> +            if (disc_exc:= self._disconnected.exception()) is not None:
Rewrite to avoid `:=` since that's a python 3.8 feature (and we still support 3.7).

...Good use case for `:=`, though. :)

2023-07-13 15:05 UTC, edenhaus commented
For tests I would wait until https://github.com/guillotinaweb/pytest-docker-fixtures/pull/33 is merged, than we have a moquitto docker container for tests. This would also fix #224

Are you fine to merge it without tests? So I can upgrade my lib to the new version and get rid of the log message about the rename

2023-07-17 20:58 UTC, empicano commented
Hi Robert, I'll ping @frederikaalund here; Maybe this got lost 😉

As a quick fix to getting rid of the log message about the rename you could restrict the version of asyncio-mqtt to `<= 0.16.1`. Version `0.16.1` is exactly the same as `0.16.2` apart from the log message.

2023-07-18 06:54 UTC, frederikaalund commented
Thanks for the ping, @empicano. Been a busy week at work due to technical issues. :)

In any case, this PR now looks good to me. :+1: Sorry about the delay in my response.

> For tests I would wait until https://github.com/guillotinaweb/pytest-docker-fixtures/pull/33 is merged, than we have a moquitto docker container for tests. This would also fix https://github.com/sbtinstruments/aiomqtt/issues/224
>
> Are you fine to merge it without tests? So I can upgrade my lib to the new version and get rid of the log message about the rename

Yes, that's completely fine with me.

Thank you for your contribution to aiomqtt.

2023-07-18 06:55 UTC, merged